name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  pull-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        run: sudo apt-get -y install build-essential
      - name: Get PostgreSQL Sources
        uses: actions/checkout@v4
        with:
          repository: HUUTFJ/postgres
      - name: Configure PostgreSQL
        run:
          cd ${{ github.workspace }}/HUUTFJ/postgres
          ./configure --enable-cassert --enable-debug
      - name: Build PostgreSQL
        run:
          make -j2
