name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  pull-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        run: sudo apt-get -y install build-essential
      - name: Get Source code
        uses: actions/checkout@4
        with:
          repository: HUUTFJ/postgres
          path: postgres
